name: Rod
main: Nathan45\Main
version: 1.0
api: [3.0.0, 4.0.0]
author: Nathan45
description: 'This plugin implements a functional fishing rod for PVP in Pocketmine-MP servers.'
website: 'https://github.com/Nathan459770'